/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivateRouteImport } from './routes/_private/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as PrivateIndexImport } from './routes/_private/index'
import { Route as PrivateWhatsappIndexImport } from './routes/_private/whatsapp/index'
import { Route as PrivateTasksIndexImport } from './routes/_private/tasks/index'
import { Route as PrivateMembersIndexImport } from './routes/_private/members/index'
import { Route as PrivateEmailIndexImport } from './routes/_private/email/index'
import { Route as PrivateCustomersIndexImport } from './routes/_private/customers/index'
import { Route as PrivateContactsIndexImport } from './routes/_private/contacts/index'
import { Route as AuthRegisterIndexImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexImport } from './routes/_auth/login/index'
import { Route as AuthRegisterOrganizationImport } from './routes/_auth/register/organization'
import { Route as PrivateCustomersIdIndexImport } from './routes/_private/customers/$id/index'
import { Route as PrivateContactsIdIndexImport } from './routes/_private/contacts/$id/index'

// Create/Update Routes

const PrivateRouteRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexRoute = PrivateIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateWhatsappIndexRoute = PrivateWhatsappIndexImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateTasksIndexRoute = PrivateTasksIndexImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateMembersIndexRoute = PrivateMembersIndexImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateEmailIndexRoute = PrivateEmailIndexImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateCustomersIndexRoute = PrivateCustomersIndexImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateContactsIndexRoute = PrivateContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const AuthRegisterIndexRoute = AuthRegisterIndexImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginIndexRoute = AuthLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthRegisterOrganizationRoute = AuthRegisterOrganizationImport.update({
  id: '/register/organization',
  path: '/register/organization',
  getParentRoute: () => AuthRouteRoute,
} as any)

const PrivateCustomersIdIndexRoute = PrivateCustomersIdIndexImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PrivateContactsIdIndexRoute = PrivateContactsIdIndexImport.update({
  id: '/contacts/$id/',
  path: '/contacts/$id/',
  getParentRoute: () => PrivateRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRoute
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_auth/register/organization': {
      id: '/_auth/register/organization'
      path: '/register/organization'
      fullPath: '/register/organization'
      preLoaderRoute: typeof AuthRegisterOrganizationImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_private/contacts/': {
      id: '/_private/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof PrivateContactsIndexImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/customers/': {
      id: '/_private/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof PrivateCustomersIndexImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/email/': {
      id: '/_private/email/'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof PrivateEmailIndexImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/members/': {
      id: '/_private/members/'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof PrivateMembersIndexImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/tasks/': {
      id: '/_private/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof PrivateTasksIndexImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/whatsapp/': {
      id: '/_private/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof PrivateWhatsappIndexImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/contacts/$id/': {
      id: '/_private/contacts/$id/'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof PrivateContactsIdIndexImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/customers/$id/': {
      id: '/_private/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof PrivateCustomersIdIndexImport
      parentRoute: typeof PrivateRouteImport
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthRegisterOrganizationRoute: typeof AuthRegisterOrganizationRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterOrganizationRoute: AuthRegisterOrganizationRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateRouteRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateContactsIndexRoute: typeof PrivateContactsIndexRoute
  PrivateCustomersIndexRoute: typeof PrivateCustomersIndexRoute
  PrivateEmailIndexRoute: typeof PrivateEmailIndexRoute
  PrivateMembersIndexRoute: typeof PrivateMembersIndexRoute
  PrivateTasksIndexRoute: typeof PrivateTasksIndexRoute
  PrivateWhatsappIndexRoute: typeof PrivateWhatsappIndexRoute
  PrivateContactsIdIndexRoute: typeof PrivateContactsIdIndexRoute
  PrivateCustomersIdIndexRoute: typeof PrivateCustomersIdIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateContactsIndexRoute: PrivateContactsIndexRoute,
  PrivateCustomersIndexRoute: PrivateCustomersIndexRoute,
  PrivateEmailIndexRoute: PrivateEmailIndexRoute,
  PrivateMembersIndexRoute: PrivateMembersIndexRoute,
  PrivateTasksIndexRoute: PrivateTasksIndexRoute,
  PrivateWhatsappIndexRoute: PrivateWhatsappIndexRoute,
  PrivateContactsIdIndexRoute: PrivateContactsIdIndexRoute,
  PrivateCustomersIdIndexRoute: PrivateCustomersIdIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PrivateRouteRouteWithChildren
  '/': typeof PrivateIndexRoute
  '/register/organization': typeof AuthRegisterOrganizationRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/contacts': typeof PrivateContactsIndexRoute
  '/customers': typeof PrivateCustomersIndexRoute
  '/email': typeof PrivateEmailIndexRoute
  '/members': typeof PrivateMembersIndexRoute
  '/tasks': typeof PrivateTasksIndexRoute
  '/whatsapp': typeof PrivateWhatsappIndexRoute
  '/contacts/$id': typeof PrivateContactsIdIndexRoute
  '/customers/$id': typeof PrivateCustomersIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AuthRouteRouteWithChildren
  '/': typeof PrivateIndexRoute
  '/register/organization': typeof AuthRegisterOrganizationRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/contacts': typeof PrivateContactsIndexRoute
  '/customers': typeof PrivateCustomersIndexRoute
  '/email': typeof PrivateEmailIndexRoute
  '/members': typeof PrivateMembersIndexRoute
  '/tasks': typeof PrivateTasksIndexRoute
  '/whatsapp': typeof PrivateWhatsappIndexRoute
  '/contacts/$id': typeof PrivateContactsIdIndexRoute
  '/customers/$id': typeof PrivateCustomersIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/_auth/register/organization': typeof AuthRegisterOrganizationRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_private/contacts/': typeof PrivateContactsIndexRoute
  '/_private/customers/': typeof PrivateCustomersIndexRoute
  '/_private/email/': typeof PrivateEmailIndexRoute
  '/_private/members/': typeof PrivateMembersIndexRoute
  '/_private/tasks/': typeof PrivateTasksIndexRoute
  '/_private/whatsapp/': typeof PrivateWhatsappIndexRoute
  '/_private/contacts/$id/': typeof PrivateContactsIdIndexRoute
  '/_private/customers/$id/': typeof PrivateCustomersIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/register/organization'
    | '/login'
    | '/register'
    | '/contacts'
    | '/customers'
    | '/email'
    | '/members'
    | '/tasks'
    | '/whatsapp'
    | '/contacts/$id'
    | '/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/register/organization'
    | '/login'
    | '/register'
    | '/contacts'
    | '/customers'
    | '/email'
    | '/members'
    | '/tasks'
    | '/whatsapp'
    | '/contacts/$id'
    | '/customers/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_private/'
    | '/_auth/register/organization'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_private/contacts/'
    | '/_private/customers/'
    | '/_private/email/'
    | '/_private/members/'
    | '/_private/tasks/'
    | '/_private/whatsapp/'
    | '/_private/contacts/$id/'
    | '/_private/customers/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_private"
      ]
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/register/organization",
        "/_auth/login/",
        "/_auth/register/"
      ]
    },
    "/_private": {
      "filePath": "_private/route.tsx",
      "children": [
        "/_private/",
        "/_private/contacts/",
        "/_private/customers/",
        "/_private/email/",
        "/_private/members/",
        "/_private/tasks/",
        "/_private/whatsapp/",
        "/_private/contacts/$id/",
        "/_private/customers/$id/"
      ]
    },
    "/_private/": {
      "filePath": "_private/index.tsx",
      "parent": "/_private"
    },
    "/_auth/register/organization": {
      "filePath": "_auth/register/organization.tsx",
      "parent": "/_auth"
    },
    "/_auth/login/": {
      "filePath": "_auth/login/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/register/": {
      "filePath": "_auth/register/index.tsx",
      "parent": "/_auth"
    },
    "/_private/contacts/": {
      "filePath": "_private/contacts/index.tsx",
      "parent": "/_private"
    },
    "/_private/customers/": {
      "filePath": "_private/customers/index.tsx",
      "parent": "/_private"
    },
    "/_private/email/": {
      "filePath": "_private/email/index.tsx",
      "parent": "/_private"
    },
    "/_private/members/": {
      "filePath": "_private/members/index.tsx",
      "parent": "/_private"
    },
    "/_private/tasks/": {
      "filePath": "_private/tasks/index.tsx",
      "parent": "/_private"
    },
    "/_private/whatsapp/": {
      "filePath": "_private/whatsapp/index.tsx",
      "parent": "/_private"
    },
    "/_private/contacts/$id/": {
      "filePath": "_private/contacts/$id/index.tsx",
      "parent": "/_private"
    },
    "/_private/customers/$id/": {
      "filePath": "_private/customers/$id/index.tsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
