/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PrivateEmployeesRouteRouteImport } from './routes/_private/employees/route'
import { Route as PrivateAssetsRouteRouteImport } from './routes/_private/assets/route'
import { Route as PrivateWhatsappIndexRouteImport } from './routes/_private/whatsapp/index'
import { Route as PrivateTasksIndexRouteImport } from './routes/_private/tasks/index'
import { Route as PrivateServicesIndexRouteImport } from './routes/_private/services/index'
import { Route as PrivateRolesIndexRouteImport } from './routes/_private/roles/index'
import { Route as PrivatePartnersIndexRouteImport } from './routes/_private/partners/index'
import { Route as PrivateMembersIndexRouteImport } from './routes/_private/members/index'
import { Route as PrivateInvoicesIndexRouteImport } from './routes/_private/invoices/index'
import { Route as PrivateEventsIndexRouteImport } from './routes/_private/events/index'
import { Route as PrivateEmployeesIndexRouteImport } from './routes/_private/employees/index'
import { Route as PrivateEmailIndexRouteImport } from './routes/_private/email/index'
import { Route as PrivateDesignationsIndexRouteImport } from './routes/_private/designations/index'
import { Route as PrivateAssetsIndexRouteImport } from './routes/_private/assets/index'
import { Route as PrivateDashboardIndexRouteImport } from './routes/_private/_dashboard/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthRegisterOrganizationRouteImport } from './routes/_auth/register/organization'
import { Route as PrivateServicesRegalTranstradeIndexRouteImport } from './routes/_private/services/regal-transtrade/index'
import { Route as PrivatePartnersRoleIndexRouteImport } from './routes/_private/partners/$role/index'
import { Route as PrivateInvoicesRegalTranstradeIndexRouteImport } from './routes/_private/invoices/regal-transtrade/index'
import { Route as PrivateEmployeesIdIndexRouteImport } from './routes/_private/employees/$id/index'
import { Route as PrivateAssetsIdIndexRouteImport } from './routes/_private/assets/$id/index'
import { Route as PrivateServicesRegalTranstradeDistrictIndexRouteImport } from './routes/_private/services/regal-transtrade/district/index'
import { Route as PrivateServicesRegalTranstradeDepotIndexRouteImport } from './routes/_private/services/regal-transtrade/depot/index'
import { Route as PrivateInvoicesRegalTranstradeIdIndexRouteImport } from './routes/_private/invoices/regal-transtrade/$id/index'
import { Route as PrivateServicesRegalTranstradeDistrictCreateIndexRouteImport } from './routes/_private/services/regal-transtrade/district/create/index'
import { Route as PrivateServicesRegalTranstradeDistrictIdIndexRouteImport } from './routes/_private/services/regal-transtrade/district/$id/index'
import { Route as PrivateServicesRegalTranstradeDepotCreateIndexRouteImport } from './routes/_private/services/regal-transtrade/depot/create/index'
import { Route as PrivateServicesRegalTranstradeDepotIdIndexRouteImport } from './routes/_private/services/regal-transtrade/depot/$id/index'
import { Route as PrivateServicesRegalTranstradeDistrictIdEditIndexRouteImport } from './routes/_private/services/regal-transtrade/district/$id/edit/index'
import { Route as PrivateServicesRegalTranstradeDepotIdEditIndexRouteImport } from './routes/_private/services/regal-transtrade/depot/$id/edit/index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateEmployeesRouteRoute = PrivateEmployeesRouteRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAssetsRouteRoute = PrivateAssetsRouteRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateWhatsappIndexRoute = PrivateWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTasksIndexRoute = PrivateTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateServicesIndexRoute = PrivateServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateRolesIndexRoute = PrivateRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivatePartnersIndexRoute = PrivatePartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMembersIndexRoute = PrivateMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateInvoicesIndexRoute = PrivateInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEventsIndexRoute = PrivateEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEmployeesIndexRoute = PrivateEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateEmployeesRouteRoute,
} as any)
const PrivateEmailIndexRoute = PrivateEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateDesignationsIndexRoute =
  PrivateDesignationsIndexRouteImport.update({
    id: '/designations/',
    path: '/designations/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateAssetsIndexRoute = PrivateAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateAssetsRouteRoute,
} as any)
const PrivateDashboardIndexRoute = PrivateDashboardIndexRouteImport.update({
  id: '/_dashboard/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterOrganizationRoute =
  AuthRegisterOrganizationRouteImport.update({
    id: '/register/organization',
    path: '/register/organization',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const PrivateServicesRegalTranstradeIndexRoute =
  PrivateServicesRegalTranstradeIndexRouteImport.update({
    id: '/services/regal-transtrade/',
    path: '/services/regal-transtrade/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivatePartnersRoleIndexRoute =
  PrivatePartnersRoleIndexRouteImport.update({
    id: '/partners/$role/',
    path: '/partners/$role/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInvoicesRegalTranstradeIndexRoute =
  PrivateInvoicesRegalTranstradeIndexRouteImport.update({
    id: '/invoices/regal-transtrade/',
    path: '/invoices/regal-transtrade/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateEmployeesIdIndexRoute = PrivateEmployeesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => PrivateEmployeesRouteRoute,
} as any)
const PrivateAssetsIdIndexRoute = PrivateAssetsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => PrivateAssetsRouteRoute,
} as any)
const PrivateServicesRegalTranstradeDistrictIndexRoute =
  PrivateServicesRegalTranstradeDistrictIndexRouteImport.update({
    id: '/services/regal-transtrade/district/',
    path: '/services/regal-transtrade/district/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateServicesRegalTranstradeDepotIndexRoute =
  PrivateServicesRegalTranstradeDepotIndexRouteImport.update({
    id: '/services/regal-transtrade/depot/',
    path: '/services/regal-transtrade/depot/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateInvoicesRegalTranstradeIdIndexRoute =
  PrivateInvoicesRegalTranstradeIdIndexRouteImport.update({
    id: '/invoices/regal-transtrade/$id/',
    path: '/invoices/regal-transtrade/$id/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateServicesRegalTranstradeDistrictCreateIndexRoute =
  PrivateServicesRegalTranstradeDistrictCreateIndexRouteImport.update({
    id: '/services/regal-transtrade/district/create/',
    path: '/services/regal-transtrade/district/create/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateServicesRegalTranstradeDistrictIdIndexRoute =
  PrivateServicesRegalTranstradeDistrictIdIndexRouteImport.update({
    id: '/services/regal-transtrade/district/$id/',
    path: '/services/regal-transtrade/district/$id/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateServicesRegalTranstradeDepotCreateIndexRoute =
  PrivateServicesRegalTranstradeDepotCreateIndexRouteImport.update({
    id: '/services/regal-transtrade/depot/create/',
    path: '/services/regal-transtrade/depot/create/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateServicesRegalTranstradeDepotIdIndexRoute =
  PrivateServicesRegalTranstradeDepotIdIndexRouteImport.update({
    id: '/services/regal-transtrade/depot/$id/',
    path: '/services/regal-transtrade/depot/$id/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateServicesRegalTranstradeDistrictIdEditIndexRoute =
  PrivateServicesRegalTranstradeDistrictIdEditIndexRouteImport.update({
    id: '/services/regal-transtrade/district/$id/edit/',
    path: '/services/regal-transtrade/district/$id/edit/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateServicesRegalTranstradeDepotIdEditIndexRoute =
  PrivateServicesRegalTranstradeDepotIdEditIndexRouteImport.update({
    id: '/services/regal-transtrade/depot/$id/edit/',
    path: '/services/regal-transtrade/depot/$id/edit/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/assets': typeof PrivateAssetsRouteRouteWithChildren
  '/employees': typeof PrivateEmployeesRouteRouteWithChildren
  '/register/organization': typeof AuthRegisterOrganizationRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/': typeof PrivateDashboardIndexRoute
  '/assets/': typeof PrivateAssetsIndexRoute
  '/designations': typeof PrivateDesignationsIndexRoute
  '/email': typeof PrivateEmailIndexRoute
  '/employees/': typeof PrivateEmployeesIndexRoute
  '/events': typeof PrivateEventsIndexRoute
  '/invoices': typeof PrivateInvoicesIndexRoute
  '/members': typeof PrivateMembersIndexRoute
  '/partners': typeof PrivatePartnersIndexRoute
  '/roles': typeof PrivateRolesIndexRoute
  '/services': typeof PrivateServicesIndexRoute
  '/tasks': typeof PrivateTasksIndexRoute
  '/whatsapp': typeof PrivateWhatsappIndexRoute
  '/assets/$id': typeof PrivateAssetsIdIndexRoute
  '/employees/$id': typeof PrivateEmployeesIdIndexRoute
  '/invoices/regal-transtrade': typeof PrivateInvoicesRegalTranstradeIndexRoute
  '/partners/$role': typeof PrivatePartnersRoleIndexRoute
  '/services/regal-transtrade': typeof PrivateServicesRegalTranstradeIndexRoute
  '/invoices/regal-transtrade/$id': typeof PrivateInvoicesRegalTranstradeIdIndexRoute
  '/services/regal-transtrade/depot': typeof PrivateServicesRegalTranstradeDepotIndexRoute
  '/services/regal-transtrade/district': typeof PrivateServicesRegalTranstradeDistrictIndexRoute
  '/services/regal-transtrade/depot/$id': typeof PrivateServicesRegalTranstradeDepotIdIndexRoute
  '/services/regal-transtrade/depot/create': typeof PrivateServicesRegalTranstradeDepotCreateIndexRoute
  '/services/regal-transtrade/district/$id': typeof PrivateServicesRegalTranstradeDistrictIdIndexRoute
  '/services/regal-transtrade/district/create': typeof PrivateServicesRegalTranstradeDistrictCreateIndexRoute
  '/services/regal-transtrade/depot/$id/edit': typeof PrivateServicesRegalTranstradeDepotIdEditIndexRoute
  '/services/regal-transtrade/district/$id/edit': typeof PrivateServicesRegalTranstradeDistrictIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/register/organization': typeof AuthRegisterOrganizationRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/': typeof PrivateDashboardIndexRoute
  '/assets': typeof PrivateAssetsIndexRoute
  '/designations': typeof PrivateDesignationsIndexRoute
  '/email': typeof PrivateEmailIndexRoute
  '/employees': typeof PrivateEmployeesIndexRoute
  '/events': typeof PrivateEventsIndexRoute
  '/invoices': typeof PrivateInvoicesIndexRoute
  '/members': typeof PrivateMembersIndexRoute
  '/partners': typeof PrivatePartnersIndexRoute
  '/roles': typeof PrivateRolesIndexRoute
  '/services': typeof PrivateServicesIndexRoute
  '/tasks': typeof PrivateTasksIndexRoute
  '/whatsapp': typeof PrivateWhatsappIndexRoute
  '/assets/$id': typeof PrivateAssetsIdIndexRoute
  '/employees/$id': typeof PrivateEmployeesIdIndexRoute
  '/invoices/regal-transtrade': typeof PrivateInvoicesRegalTranstradeIndexRoute
  '/partners/$role': typeof PrivatePartnersRoleIndexRoute
  '/services/regal-transtrade': typeof PrivateServicesRegalTranstradeIndexRoute
  '/invoices/regal-transtrade/$id': typeof PrivateInvoicesRegalTranstradeIdIndexRoute
  '/services/regal-transtrade/depot': typeof PrivateServicesRegalTranstradeDepotIndexRoute
  '/services/regal-transtrade/district': typeof PrivateServicesRegalTranstradeDistrictIndexRoute
  '/services/regal-transtrade/depot/$id': typeof PrivateServicesRegalTranstradeDepotIdIndexRoute
  '/services/regal-transtrade/depot/create': typeof PrivateServicesRegalTranstradeDepotCreateIndexRoute
  '/services/regal-transtrade/district/$id': typeof PrivateServicesRegalTranstradeDistrictIdIndexRoute
  '/services/regal-transtrade/district/create': typeof PrivateServicesRegalTranstradeDistrictCreateIndexRoute
  '/services/regal-transtrade/depot/$id/edit': typeof PrivateServicesRegalTranstradeDepotIdEditIndexRoute
  '/services/regal-transtrade/district/$id/edit': typeof PrivateServicesRegalTranstradeDistrictIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_private/assets': typeof PrivateAssetsRouteRouteWithChildren
  '/_private/employees': typeof PrivateEmployeesRouteRouteWithChildren
  '/_auth/register/organization': typeof AuthRegisterOrganizationRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_private/_dashboard/': typeof PrivateDashboardIndexRoute
  '/_private/assets/': typeof PrivateAssetsIndexRoute
  '/_private/designations/': typeof PrivateDesignationsIndexRoute
  '/_private/email/': typeof PrivateEmailIndexRoute
  '/_private/employees/': typeof PrivateEmployeesIndexRoute
  '/_private/events/': typeof PrivateEventsIndexRoute
  '/_private/invoices/': typeof PrivateInvoicesIndexRoute
  '/_private/members/': typeof PrivateMembersIndexRoute
  '/_private/partners/': typeof PrivatePartnersIndexRoute
  '/_private/roles/': typeof PrivateRolesIndexRoute
  '/_private/services/': typeof PrivateServicesIndexRoute
  '/_private/tasks/': typeof PrivateTasksIndexRoute
  '/_private/whatsapp/': typeof PrivateWhatsappIndexRoute
  '/_private/assets/$id/': typeof PrivateAssetsIdIndexRoute
  '/_private/employees/$id/': typeof PrivateEmployeesIdIndexRoute
  '/_private/invoices/regal-transtrade/': typeof PrivateInvoicesRegalTranstradeIndexRoute
  '/_private/partners/$role/': typeof PrivatePartnersRoleIndexRoute
  '/_private/services/regal-transtrade/': typeof PrivateServicesRegalTranstradeIndexRoute
  '/_private/invoices/regal-transtrade/$id/': typeof PrivateInvoicesRegalTranstradeIdIndexRoute
  '/_private/services/regal-transtrade/depot/': typeof PrivateServicesRegalTranstradeDepotIndexRoute
  '/_private/services/regal-transtrade/district/': typeof PrivateServicesRegalTranstradeDistrictIndexRoute
  '/_private/services/regal-transtrade/depot/$id/': typeof PrivateServicesRegalTranstradeDepotIdIndexRoute
  '/_private/services/regal-transtrade/depot/create/': typeof PrivateServicesRegalTranstradeDepotCreateIndexRoute
  '/_private/services/regal-transtrade/district/$id/': typeof PrivateServicesRegalTranstradeDistrictIdIndexRoute
  '/_private/services/regal-transtrade/district/create/': typeof PrivateServicesRegalTranstradeDistrictCreateIndexRoute
  '/_private/services/regal-transtrade/depot/$id/edit/': typeof PrivateServicesRegalTranstradeDepotIdEditIndexRoute
  '/_private/services/regal-transtrade/district/$id/edit/': typeof PrivateServicesRegalTranstradeDistrictIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assets'
    | '/employees'
    | '/register/organization'
    | '/login'
    | '/register'
    | '/'
    | '/assets/'
    | '/designations'
    | '/email'
    | '/employees/'
    | '/events'
    | '/invoices'
    | '/members'
    | '/partners'
    | '/roles'
    | '/services'
    | '/tasks'
    | '/whatsapp'
    | '/assets/$id'
    | '/employees/$id'
    | '/invoices/regal-transtrade'
    | '/partners/$role'
    | '/services/regal-transtrade'
    | '/invoices/regal-transtrade/$id'
    | '/services/regal-transtrade/depot'
    | '/services/regal-transtrade/district'
    | '/services/regal-transtrade/depot/$id'
    | '/services/regal-transtrade/depot/create'
    | '/services/regal-transtrade/district/$id'
    | '/services/regal-transtrade/district/create'
    | '/services/regal-transtrade/depot/$id/edit'
    | '/services/regal-transtrade/district/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/register/organization'
    | '/login'
    | '/register'
    | '/'
    | '/assets'
    | '/designations'
    | '/email'
    | '/employees'
    | '/events'
    | '/invoices'
    | '/members'
    | '/partners'
    | '/roles'
    | '/services'
    | '/tasks'
    | '/whatsapp'
    | '/assets/$id'
    | '/employees/$id'
    | '/invoices/regal-transtrade'
    | '/partners/$role'
    | '/services/regal-transtrade'
    | '/invoices/regal-transtrade/$id'
    | '/services/regal-transtrade/depot'
    | '/services/regal-transtrade/district'
    | '/services/regal-transtrade/depot/$id'
    | '/services/regal-transtrade/depot/create'
    | '/services/regal-transtrade/district/$id'
    | '/services/regal-transtrade/district/create'
    | '/services/regal-transtrade/depot/$id/edit'
    | '/services/regal-transtrade/district/$id/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_private/assets'
    | '/_private/employees'
    | '/_auth/register/organization'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_private/_dashboard/'
    | '/_private/assets/'
    | '/_private/designations/'
    | '/_private/email/'
    | '/_private/employees/'
    | '/_private/events/'
    | '/_private/invoices/'
    | '/_private/members/'
    | '/_private/partners/'
    | '/_private/roles/'
    | '/_private/services/'
    | '/_private/tasks/'
    | '/_private/whatsapp/'
    | '/_private/assets/$id/'
    | '/_private/employees/$id/'
    | '/_private/invoices/regal-transtrade/'
    | '/_private/partners/$role/'
    | '/_private/services/regal-transtrade/'
    | '/_private/invoices/regal-transtrade/$id/'
    | '/_private/services/regal-transtrade/depot/'
    | '/_private/services/regal-transtrade/district/'
    | '/_private/services/regal-transtrade/depot/$id/'
    | '/_private/services/regal-transtrade/depot/create/'
    | '/_private/services/regal-transtrade/district/$id/'
    | '/_private/services/regal-transtrade/district/create/'
    | '/_private/services/regal-transtrade/depot/$id/edit/'
    | '/_private/services/regal-transtrade/district/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/employees': {
      id: '/_private/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof PrivateEmployeesRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/assets': {
      id: '/_private/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof PrivateAssetsRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/whatsapp/': {
      id: '/_private/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof PrivateWhatsappIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tasks/': {
      id: '/_private/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof PrivateTasksIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/services/': {
      id: '/_private/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PrivateServicesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/roles/': {
      id: '/_private/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof PrivateRolesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/partners/': {
      id: '/_private/partners/'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PrivatePartnersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/members/': {
      id: '/_private/members/'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof PrivateMembersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/invoices/': {
      id: '/_private/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof PrivateInvoicesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/events/': {
      id: '/_private/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PrivateEventsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employees/': {
      id: '/_private/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof PrivateEmployeesIndexRouteImport
      parentRoute: typeof PrivateEmployeesRouteRoute
    }
    '/_private/email/': {
      id: '/_private/email/'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof PrivateEmailIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/designations/': {
      id: '/_private/designations/'
      path: '/designations'
      fullPath: '/designations'
      preLoaderRoute: typeof PrivateDesignationsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/assets/': {
      id: '/_private/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof PrivateAssetsIndexRouteImport
      parentRoute: typeof PrivateAssetsRouteRoute
    }
    '/_private/_dashboard/': {
      id: '/_private/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateDashboardIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/organization': {
      id: '/_auth/register/organization'
      path: '/register/organization'
      fullPath: '/register/organization'
      preLoaderRoute: typeof AuthRegisterOrganizationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_private/services/regal-transtrade/': {
      id: '/_private/services/regal-transtrade/'
      path: '/services/regal-transtrade'
      fullPath: '/services/regal-transtrade'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/partners/$role/': {
      id: '/_private/partners/$role/'
      path: '/partners/$role'
      fullPath: '/partners/$role'
      preLoaderRoute: typeof PrivatePartnersRoleIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/invoices/regal-transtrade/': {
      id: '/_private/invoices/regal-transtrade/'
      path: '/invoices/regal-transtrade'
      fullPath: '/invoices/regal-transtrade'
      preLoaderRoute: typeof PrivateInvoicesRegalTranstradeIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employees/$id/': {
      id: '/_private/employees/$id/'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof PrivateEmployeesIdIndexRouteImport
      parentRoute: typeof PrivateEmployeesRouteRoute
    }
    '/_private/assets/$id/': {
      id: '/_private/assets/$id/'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof PrivateAssetsIdIndexRouteImport
      parentRoute: typeof PrivateAssetsRouteRoute
    }
    '/_private/services/regal-transtrade/district/': {
      id: '/_private/services/regal-transtrade/district/'
      path: '/services/regal-transtrade/district'
      fullPath: '/services/regal-transtrade/district'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeDistrictIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/services/regal-transtrade/depot/': {
      id: '/_private/services/regal-transtrade/depot/'
      path: '/services/regal-transtrade/depot'
      fullPath: '/services/regal-transtrade/depot'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeDepotIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/invoices/regal-transtrade/$id/': {
      id: '/_private/invoices/regal-transtrade/$id/'
      path: '/invoices/regal-transtrade/$id'
      fullPath: '/invoices/regal-transtrade/$id'
      preLoaderRoute: typeof PrivateInvoicesRegalTranstradeIdIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/services/regal-transtrade/district/create/': {
      id: '/_private/services/regal-transtrade/district/create/'
      path: '/services/regal-transtrade/district/create'
      fullPath: '/services/regal-transtrade/district/create'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeDistrictCreateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/services/regal-transtrade/district/$id/': {
      id: '/_private/services/regal-transtrade/district/$id/'
      path: '/services/regal-transtrade/district/$id'
      fullPath: '/services/regal-transtrade/district/$id'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeDistrictIdIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/services/regal-transtrade/depot/create/': {
      id: '/_private/services/regal-transtrade/depot/create/'
      path: '/services/regal-transtrade/depot/create'
      fullPath: '/services/regal-transtrade/depot/create'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeDepotCreateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/services/regal-transtrade/depot/$id/': {
      id: '/_private/services/regal-transtrade/depot/$id/'
      path: '/services/regal-transtrade/depot/$id'
      fullPath: '/services/regal-transtrade/depot/$id'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeDepotIdIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/services/regal-transtrade/district/$id/edit/': {
      id: '/_private/services/regal-transtrade/district/$id/edit/'
      path: '/services/regal-transtrade/district/$id/edit'
      fullPath: '/services/regal-transtrade/district/$id/edit'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeDistrictIdEditIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/services/regal-transtrade/depot/$id/edit/': {
      id: '/_private/services/regal-transtrade/depot/$id/edit/'
      path: '/services/regal-transtrade/depot/$id/edit'
      fullPath: '/services/regal-transtrade/depot/$id/edit'
      preLoaderRoute: typeof PrivateServicesRegalTranstradeDepotIdEditIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthRegisterOrganizationRoute: typeof AuthRegisterOrganizationRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterOrganizationRoute: AuthRegisterOrganizationRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateAssetsRouteRouteChildren {
  PrivateAssetsIndexRoute: typeof PrivateAssetsIndexRoute
  PrivateAssetsIdIndexRoute: typeof PrivateAssetsIdIndexRoute
}

const PrivateAssetsRouteRouteChildren: PrivateAssetsRouteRouteChildren = {
  PrivateAssetsIndexRoute: PrivateAssetsIndexRoute,
  PrivateAssetsIdIndexRoute: PrivateAssetsIdIndexRoute,
}

const PrivateAssetsRouteRouteWithChildren =
  PrivateAssetsRouteRoute._addFileChildren(PrivateAssetsRouteRouteChildren)

interface PrivateEmployeesRouteRouteChildren {
  PrivateEmployeesIndexRoute: typeof PrivateEmployeesIndexRoute
  PrivateEmployeesIdIndexRoute: typeof PrivateEmployeesIdIndexRoute
}

const PrivateEmployeesRouteRouteChildren: PrivateEmployeesRouteRouteChildren = {
  PrivateEmployeesIndexRoute: PrivateEmployeesIndexRoute,
  PrivateEmployeesIdIndexRoute: PrivateEmployeesIdIndexRoute,
}

const PrivateEmployeesRouteRouteWithChildren =
  PrivateEmployeesRouteRoute._addFileChildren(
    PrivateEmployeesRouteRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateAssetsRouteRoute: typeof PrivateAssetsRouteRouteWithChildren
  PrivateEmployeesRouteRoute: typeof PrivateEmployeesRouteRouteWithChildren
  PrivateDashboardIndexRoute: typeof PrivateDashboardIndexRoute
  PrivateDesignationsIndexRoute: typeof PrivateDesignationsIndexRoute
  PrivateEmailIndexRoute: typeof PrivateEmailIndexRoute
  PrivateEventsIndexRoute: typeof PrivateEventsIndexRoute
  PrivateInvoicesIndexRoute: typeof PrivateInvoicesIndexRoute
  PrivateMembersIndexRoute: typeof PrivateMembersIndexRoute
  PrivatePartnersIndexRoute: typeof PrivatePartnersIndexRoute
  PrivateRolesIndexRoute: typeof PrivateRolesIndexRoute
  PrivateServicesIndexRoute: typeof PrivateServicesIndexRoute
  PrivateTasksIndexRoute: typeof PrivateTasksIndexRoute
  PrivateWhatsappIndexRoute: typeof PrivateWhatsappIndexRoute
  PrivateInvoicesRegalTranstradeIndexRoute: typeof PrivateInvoicesRegalTranstradeIndexRoute
  PrivatePartnersRoleIndexRoute: typeof PrivatePartnersRoleIndexRoute
  PrivateServicesRegalTranstradeIndexRoute: typeof PrivateServicesRegalTranstradeIndexRoute
  PrivateInvoicesRegalTranstradeIdIndexRoute: typeof PrivateInvoicesRegalTranstradeIdIndexRoute
  PrivateServicesRegalTranstradeDepotIndexRoute: typeof PrivateServicesRegalTranstradeDepotIndexRoute
  PrivateServicesRegalTranstradeDistrictIndexRoute: typeof PrivateServicesRegalTranstradeDistrictIndexRoute
  PrivateServicesRegalTranstradeDepotIdIndexRoute: typeof PrivateServicesRegalTranstradeDepotIdIndexRoute
  PrivateServicesRegalTranstradeDepotCreateIndexRoute: typeof PrivateServicesRegalTranstradeDepotCreateIndexRoute
  PrivateServicesRegalTranstradeDistrictIdIndexRoute: typeof PrivateServicesRegalTranstradeDistrictIdIndexRoute
  PrivateServicesRegalTranstradeDistrictCreateIndexRoute: typeof PrivateServicesRegalTranstradeDistrictCreateIndexRoute
  PrivateServicesRegalTranstradeDepotIdEditIndexRoute: typeof PrivateServicesRegalTranstradeDepotIdEditIndexRoute
  PrivateServicesRegalTranstradeDistrictIdEditIndexRoute: typeof PrivateServicesRegalTranstradeDistrictIdEditIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAssetsRouteRoute: PrivateAssetsRouteRouteWithChildren,
  PrivateEmployeesRouteRoute: PrivateEmployeesRouteRouteWithChildren,
  PrivateDashboardIndexRoute: PrivateDashboardIndexRoute,
  PrivateDesignationsIndexRoute: PrivateDesignationsIndexRoute,
  PrivateEmailIndexRoute: PrivateEmailIndexRoute,
  PrivateEventsIndexRoute: PrivateEventsIndexRoute,
  PrivateInvoicesIndexRoute: PrivateInvoicesIndexRoute,
  PrivateMembersIndexRoute: PrivateMembersIndexRoute,
  PrivatePartnersIndexRoute: PrivatePartnersIndexRoute,
  PrivateRolesIndexRoute: PrivateRolesIndexRoute,
  PrivateServicesIndexRoute: PrivateServicesIndexRoute,
  PrivateTasksIndexRoute: PrivateTasksIndexRoute,
  PrivateWhatsappIndexRoute: PrivateWhatsappIndexRoute,
  PrivateInvoicesRegalTranstradeIndexRoute:
    PrivateInvoicesRegalTranstradeIndexRoute,
  PrivatePartnersRoleIndexRoute: PrivatePartnersRoleIndexRoute,
  PrivateServicesRegalTranstradeIndexRoute:
    PrivateServicesRegalTranstradeIndexRoute,
  PrivateInvoicesRegalTranstradeIdIndexRoute:
    PrivateInvoicesRegalTranstradeIdIndexRoute,
  PrivateServicesRegalTranstradeDepotIndexRoute:
    PrivateServicesRegalTranstradeDepotIndexRoute,
  PrivateServicesRegalTranstradeDistrictIndexRoute:
    PrivateServicesRegalTranstradeDistrictIndexRoute,
  PrivateServicesRegalTranstradeDepotIdIndexRoute:
    PrivateServicesRegalTranstradeDepotIdIndexRoute,
  PrivateServicesRegalTranstradeDepotCreateIndexRoute:
    PrivateServicesRegalTranstradeDepotCreateIndexRoute,
  PrivateServicesRegalTranstradeDistrictIdIndexRoute:
    PrivateServicesRegalTranstradeDistrictIdIndexRoute,
  PrivateServicesRegalTranstradeDistrictCreateIndexRoute:
    PrivateServicesRegalTranstradeDistrictCreateIndexRoute,
  PrivateServicesRegalTranstradeDepotIdEditIndexRoute:
    PrivateServicesRegalTranstradeDepotIdEditIndexRoute,
  PrivateServicesRegalTranstradeDistrictIdEditIndexRoute:
    PrivateServicesRegalTranstradeDistrictIdEditIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
