/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateRouteRouteImport } from './routes/_private/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PrivateEmployeesRouteRouteImport } from './routes/_private/employees/route'
import { Route as PrivateAssetsRouteRouteImport } from './routes/_private/assets/route'
import { Route as PrivateWhatsappIndexRouteImport } from './routes/_private/whatsapp/index'
import { Route as PrivateTripsIndexRouteImport } from './routes/_private/trips/index'
import { Route as PrivateTasksIndexRouteImport } from './routes/_private/tasks/index'
import { Route as PrivateRolesIndexRouteImport } from './routes/_private/roles/index'
import { Route as PrivateMembersIndexRouteImport } from './routes/_private/members/index'
import { Route as PrivateEmployeesIndexRouteImport } from './routes/_private/employees/index'
import { Route as PrivateEmailIndexRouteImport } from './routes/_private/email/index'
import { Route as PrivateDesignationsIndexRouteImport } from './routes/_private/designations/index'
import { Route as PrivateCustomersIndexRouteImport } from './routes/_private/customers/index'
import { Route as PrivateContactsIndexRouteImport } from './routes/_private/contacts/index'
import { Route as PrivateAssetsIndexRouteImport } from './routes/_private/assets/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/_auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthRegisterOrganizationRouteImport } from './routes/_auth/register/organization'
import { Route as PrivateTripsDistrictIndexRouteImport } from './routes/_private/trips/district/index'
import { Route as PrivateTripsDepotIndexRouteImport } from './routes/_private/trips/depot/index'
import { Route as PrivateEmployeesIdIndexRouteImport } from './routes/_private/employees/$id/index'
import { Route as PrivateCustomersIdIndexRouteImport } from './routes/_private/customers/$id/index'
import { Route as PrivateContactsIdIndexRouteImport } from './routes/_private/contacts/$id/index'
import { Route as PrivateAssetsIdIndexRouteImport } from './routes/_private/assets/$id/index'
import { Route as PrivateTripsDepotCreateIndexRouteImport } from './routes/_private/trips/depot/create/index'
import { Route as PrivateTripsDepotIdIndexRouteImport } from './routes/_private/trips/depot/$id/index'
import { Route as PrivateTripsDepotIdEditIndexRouteImport } from './routes/_private/trips/depot/$id/edit/index'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const PrivateRouteRoute = PrivateRouteRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEmployeesRouteRoute = PrivateEmployeesRouteRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAssetsRouteRoute = PrivateAssetsRouteRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateWhatsappIndexRoute = PrivateWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTripsIndexRoute = PrivateTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateTasksIndexRoute = PrivateTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateRolesIndexRoute = PrivateRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateMembersIndexRoute = PrivateMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEmployeesIndexRoute = PrivateEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateEmployeesRouteRoute,
} as any)
const PrivateEmailIndexRoute = PrivateEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateDesignationsIndexRoute =
  PrivateDesignationsIndexRouteImport.update({
    id: '/designations/',
    path: '/designations/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateCustomersIndexRoute = PrivateCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateContactsIndexRoute = PrivateContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAssetsIndexRoute = PrivateAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateAssetsRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterOrganizationRoute =
  AuthRegisterOrganizationRouteImport.update({
    id: '/register/organization',
    path: '/register/organization',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const PrivateTripsDistrictIndexRoute =
  PrivateTripsDistrictIndexRouteImport.update({
    id: '/trips/district/',
    path: '/trips/district/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTripsDepotIndexRoute = PrivateTripsDepotIndexRouteImport.update({
  id: '/trips/depot/',
  path: '/trips/depot/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateEmployeesIdIndexRoute = PrivateEmployeesIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => PrivateEmployeesRouteRoute,
} as any)
const PrivateCustomersIdIndexRoute = PrivateCustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateContactsIdIndexRoute = PrivateContactsIdIndexRouteImport.update({
  id: '/contacts/$id/',
  path: '/contacts/$id/',
  getParentRoute: () => PrivateRouteRoute,
} as any)
const PrivateAssetsIdIndexRoute = PrivateAssetsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => PrivateAssetsRouteRoute,
} as any)
const PrivateTripsDepotCreateIndexRoute =
  PrivateTripsDepotCreateIndexRouteImport.update({
    id: '/trips/depot/create/',
    path: '/trips/depot/create/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTripsDepotIdIndexRoute =
  PrivateTripsDepotIdIndexRouteImport.update({
    id: '/trips/depot/$id/',
    path: '/trips/depot/$id/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const PrivateTripsDepotIdEditIndexRoute =
  PrivateTripsDepotIdEditIndexRouteImport.update({
    id: '/trips/depot/$id/edit/',
    path: '/trips/depot/$id/edit/',
    getParentRoute: () => PrivateRouteRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/assets': typeof PrivateAssetsRouteRouteWithChildren
  '/employees': typeof PrivateEmployeesRouteRouteWithChildren
  '/': typeof PrivateIndexRoute
  '/register/organization': typeof AuthRegisterOrganizationRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/assets/': typeof PrivateAssetsIndexRoute
  '/contacts': typeof PrivateContactsIndexRoute
  '/customers': typeof PrivateCustomersIndexRoute
  '/designations': typeof PrivateDesignationsIndexRoute
  '/email': typeof PrivateEmailIndexRoute
  '/employees/': typeof PrivateEmployeesIndexRoute
  '/members': typeof PrivateMembersIndexRoute
  '/roles': typeof PrivateRolesIndexRoute
  '/tasks': typeof PrivateTasksIndexRoute
  '/trips': typeof PrivateTripsIndexRoute
  '/whatsapp': typeof PrivateWhatsappIndexRoute
  '/assets/$id': typeof PrivateAssetsIdIndexRoute
  '/contacts/$id': typeof PrivateContactsIdIndexRoute
  '/customers/$id': typeof PrivateCustomersIdIndexRoute
  '/employees/$id': typeof PrivateEmployeesIdIndexRoute
  '/trips/depot': typeof PrivateTripsDepotIndexRoute
  '/trips/district': typeof PrivateTripsDistrictIndexRoute
  '/trips/depot/$id': typeof PrivateTripsDepotIdIndexRoute
  '/trips/depot/create': typeof PrivateTripsDepotCreateIndexRoute
  '/trips/depot/$id/edit': typeof PrivateTripsDepotIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/register/organization': typeof AuthRegisterOrganizationRoute
  '/login': typeof AuthLoginIndexRoute
  '/register': typeof AuthRegisterIndexRoute
  '/assets': typeof PrivateAssetsIndexRoute
  '/contacts': typeof PrivateContactsIndexRoute
  '/customers': typeof PrivateCustomersIndexRoute
  '/designations': typeof PrivateDesignationsIndexRoute
  '/email': typeof PrivateEmailIndexRoute
  '/employees': typeof PrivateEmployeesIndexRoute
  '/members': typeof PrivateMembersIndexRoute
  '/roles': typeof PrivateRolesIndexRoute
  '/tasks': typeof PrivateTasksIndexRoute
  '/trips': typeof PrivateTripsIndexRoute
  '/whatsapp': typeof PrivateWhatsappIndexRoute
  '/assets/$id': typeof PrivateAssetsIdIndexRoute
  '/contacts/$id': typeof PrivateContactsIdIndexRoute
  '/customers/$id': typeof PrivateCustomersIdIndexRoute
  '/employees/$id': typeof PrivateEmployeesIdIndexRoute
  '/trips/depot': typeof PrivateTripsDepotIndexRoute
  '/trips/district': typeof PrivateTripsDistrictIndexRoute
  '/trips/depot/$id': typeof PrivateTripsDepotIdIndexRoute
  '/trips/depot/create': typeof PrivateTripsDepotCreateIndexRoute
  '/trips/depot/$id/edit': typeof PrivateTripsDepotIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_private/assets': typeof PrivateAssetsRouteRouteWithChildren
  '/_private/employees': typeof PrivateEmployeesRouteRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/_auth/register/organization': typeof AuthRegisterOrganizationRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/register/': typeof AuthRegisterIndexRoute
  '/_private/assets/': typeof PrivateAssetsIndexRoute
  '/_private/contacts/': typeof PrivateContactsIndexRoute
  '/_private/customers/': typeof PrivateCustomersIndexRoute
  '/_private/designations/': typeof PrivateDesignationsIndexRoute
  '/_private/email/': typeof PrivateEmailIndexRoute
  '/_private/employees/': typeof PrivateEmployeesIndexRoute
  '/_private/members/': typeof PrivateMembersIndexRoute
  '/_private/roles/': typeof PrivateRolesIndexRoute
  '/_private/tasks/': typeof PrivateTasksIndexRoute
  '/_private/trips/': typeof PrivateTripsIndexRoute
  '/_private/whatsapp/': typeof PrivateWhatsappIndexRoute
  '/_private/assets/$id/': typeof PrivateAssetsIdIndexRoute
  '/_private/contacts/$id/': typeof PrivateContactsIdIndexRoute
  '/_private/customers/$id/': typeof PrivateCustomersIdIndexRoute
  '/_private/employees/$id/': typeof PrivateEmployeesIdIndexRoute
  '/_private/trips/depot/': typeof PrivateTripsDepotIndexRoute
  '/_private/trips/district/': typeof PrivateTripsDistrictIndexRoute
  '/_private/trips/depot/$id/': typeof PrivateTripsDepotIdIndexRoute
  '/_private/trips/depot/create/': typeof PrivateTripsDepotCreateIndexRoute
  '/_private/trips/depot/$id/edit/': typeof PrivateTripsDepotIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/assets'
    | '/employees'
    | '/'
    | '/register/organization'
    | '/login'
    | '/register'
    | '/assets/'
    | '/contacts'
    | '/customers'
    | '/designations'
    | '/email'
    | '/employees/'
    | '/members'
    | '/roles'
    | '/tasks'
    | '/trips'
    | '/whatsapp'
    | '/assets/$id'
    | '/contacts/$id'
    | '/customers/$id'
    | '/employees/$id'
    | '/trips/depot'
    | '/trips/district'
    | '/trips/depot/$id'
    | '/trips/depot/create'
    | '/trips/depot/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register/organization'
    | '/login'
    | '/register'
    | '/assets'
    | '/contacts'
    | '/customers'
    | '/designations'
    | '/email'
    | '/employees'
    | '/members'
    | '/roles'
    | '/tasks'
    | '/trips'
    | '/whatsapp'
    | '/assets/$id'
    | '/contacts/$id'
    | '/customers/$id'
    | '/employees/$id'
    | '/trips/depot'
    | '/trips/district'
    | '/trips/depot/$id'
    | '/trips/depot/create'
    | '/trips/depot/$id/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_private/assets'
    | '/_private/employees'
    | '/_private/'
    | '/_auth/register/organization'
    | '/_auth/login/'
    | '/_auth/register/'
    | '/_private/assets/'
    | '/_private/contacts/'
    | '/_private/customers/'
    | '/_private/designations/'
    | '/_private/email/'
    | '/_private/employees/'
    | '/_private/members/'
    | '/_private/roles/'
    | '/_private/tasks/'
    | '/_private/trips/'
    | '/_private/whatsapp/'
    | '/_private/assets/$id/'
    | '/_private/contacts/$id/'
    | '/_private/customers/$id/'
    | '/_private/employees/$id/'
    | '/_private/trips/depot/'
    | '/_private/trips/district/'
    | '/_private/trips/depot/$id/'
    | '/_private/trips/depot/create/'
    | '/_private/trips/depot/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employees': {
      id: '/_private/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof PrivateEmployeesRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/assets': {
      id: '/_private/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof PrivateAssetsRouteRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/whatsapp/': {
      id: '/_private/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof PrivateWhatsappIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/trips/': {
      id: '/_private/trips/'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof PrivateTripsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/tasks/': {
      id: '/_private/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof PrivateTasksIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/roles/': {
      id: '/_private/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof PrivateRolesIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/members/': {
      id: '/_private/members/'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof PrivateMembersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employees/': {
      id: '/_private/employees/'
      path: '/'
      fullPath: '/employees/'
      preLoaderRoute: typeof PrivateEmployeesIndexRouteImport
      parentRoute: typeof PrivateEmployeesRouteRoute
    }
    '/_private/email/': {
      id: '/_private/email/'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof PrivateEmailIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/designations/': {
      id: '/_private/designations/'
      path: '/designations'
      fullPath: '/designations'
      preLoaderRoute: typeof PrivateDesignationsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/customers/': {
      id: '/_private/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof PrivateCustomersIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/contacts/': {
      id: '/_private/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof PrivateContactsIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/assets/': {
      id: '/_private/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof PrivateAssetsIndexRouteImport
      parentRoute: typeof PrivateAssetsRouteRoute
    }
    '/_auth/register/': {
      id: '/_auth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register/organization': {
      id: '/_auth/register/organization'
      path: '/register/organization'
      fullPath: '/register/organization'
      preLoaderRoute: typeof AuthRegisterOrganizationRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_private/trips/district/': {
      id: '/_private/trips/district/'
      path: '/trips/district'
      fullPath: '/trips/district'
      preLoaderRoute: typeof PrivateTripsDistrictIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/trips/depot/': {
      id: '/_private/trips/depot/'
      path: '/trips/depot'
      fullPath: '/trips/depot'
      preLoaderRoute: typeof PrivateTripsDepotIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/employees/$id/': {
      id: '/_private/employees/$id/'
      path: '/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof PrivateEmployeesIdIndexRouteImport
      parentRoute: typeof PrivateEmployeesRouteRoute
    }
    '/_private/customers/$id/': {
      id: '/_private/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof PrivateCustomersIdIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/contacts/$id/': {
      id: '/_private/contacts/$id/'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof PrivateContactsIdIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/assets/$id/': {
      id: '/_private/assets/$id/'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof PrivateAssetsIdIndexRouteImport
      parentRoute: typeof PrivateAssetsRouteRoute
    }
    '/_private/trips/depot/create/': {
      id: '/_private/trips/depot/create/'
      path: '/trips/depot/create'
      fullPath: '/trips/depot/create'
      preLoaderRoute: typeof PrivateTripsDepotCreateIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/trips/depot/$id/': {
      id: '/_private/trips/depot/$id/'
      path: '/trips/depot/$id'
      fullPath: '/trips/depot/$id'
      preLoaderRoute: typeof PrivateTripsDepotIdIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
    '/_private/trips/depot/$id/edit/': {
      id: '/_private/trips/depot/$id/edit/'
      path: '/trips/depot/$id/edit'
      fullPath: '/trips/depot/$id/edit'
      preLoaderRoute: typeof PrivateTripsDepotIdEditIndexRouteImport
      parentRoute: typeof PrivateRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthRegisterOrganizationRoute: typeof AuthRegisterOrganizationRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterOrganizationRoute: AuthRegisterOrganizationRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PrivateAssetsRouteRouteChildren {
  PrivateAssetsIndexRoute: typeof PrivateAssetsIndexRoute
  PrivateAssetsIdIndexRoute: typeof PrivateAssetsIdIndexRoute
}

const PrivateAssetsRouteRouteChildren: PrivateAssetsRouteRouteChildren = {
  PrivateAssetsIndexRoute: PrivateAssetsIndexRoute,
  PrivateAssetsIdIndexRoute: PrivateAssetsIdIndexRoute,
}

const PrivateAssetsRouteRouteWithChildren =
  PrivateAssetsRouteRoute._addFileChildren(PrivateAssetsRouteRouteChildren)

interface PrivateEmployeesRouteRouteChildren {
  PrivateEmployeesIndexRoute: typeof PrivateEmployeesIndexRoute
  PrivateEmployeesIdIndexRoute: typeof PrivateEmployeesIdIndexRoute
}

const PrivateEmployeesRouteRouteChildren: PrivateEmployeesRouteRouteChildren = {
  PrivateEmployeesIndexRoute: PrivateEmployeesIndexRoute,
  PrivateEmployeesIdIndexRoute: PrivateEmployeesIdIndexRoute,
}

const PrivateEmployeesRouteRouteWithChildren =
  PrivateEmployeesRouteRoute._addFileChildren(
    PrivateEmployeesRouteRouteChildren,
  )

interface PrivateRouteRouteChildren {
  PrivateAssetsRouteRoute: typeof PrivateAssetsRouteRouteWithChildren
  PrivateEmployeesRouteRoute: typeof PrivateEmployeesRouteRouteWithChildren
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateContactsIndexRoute: typeof PrivateContactsIndexRoute
  PrivateCustomersIndexRoute: typeof PrivateCustomersIndexRoute
  PrivateDesignationsIndexRoute: typeof PrivateDesignationsIndexRoute
  PrivateEmailIndexRoute: typeof PrivateEmailIndexRoute
  PrivateMembersIndexRoute: typeof PrivateMembersIndexRoute
  PrivateRolesIndexRoute: typeof PrivateRolesIndexRoute
  PrivateTasksIndexRoute: typeof PrivateTasksIndexRoute
  PrivateTripsIndexRoute: typeof PrivateTripsIndexRoute
  PrivateWhatsappIndexRoute: typeof PrivateWhatsappIndexRoute
  PrivateContactsIdIndexRoute: typeof PrivateContactsIdIndexRoute
  PrivateCustomersIdIndexRoute: typeof PrivateCustomersIdIndexRoute
  PrivateTripsDepotIndexRoute: typeof PrivateTripsDepotIndexRoute
  PrivateTripsDistrictIndexRoute: typeof PrivateTripsDistrictIndexRoute
  PrivateTripsDepotIdIndexRoute: typeof PrivateTripsDepotIdIndexRoute
  PrivateTripsDepotCreateIndexRoute: typeof PrivateTripsDepotCreateIndexRoute
  PrivateTripsDepotIdEditIndexRoute: typeof PrivateTripsDepotIdEditIndexRoute
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateAssetsRouteRoute: PrivateAssetsRouteRouteWithChildren,
  PrivateEmployeesRouteRoute: PrivateEmployeesRouteRouteWithChildren,
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateContactsIndexRoute: PrivateContactsIndexRoute,
  PrivateCustomersIndexRoute: PrivateCustomersIndexRoute,
  PrivateDesignationsIndexRoute: PrivateDesignationsIndexRoute,
  PrivateEmailIndexRoute: PrivateEmailIndexRoute,
  PrivateMembersIndexRoute: PrivateMembersIndexRoute,
  PrivateRolesIndexRoute: PrivateRolesIndexRoute,
  PrivateTasksIndexRoute: PrivateTasksIndexRoute,
  PrivateTripsIndexRoute: PrivateTripsIndexRoute,
  PrivateWhatsappIndexRoute: PrivateWhatsappIndexRoute,
  PrivateContactsIdIndexRoute: PrivateContactsIdIndexRoute,
  PrivateCustomersIdIndexRoute: PrivateCustomersIdIndexRoute,
  PrivateTripsDepotIndexRoute: PrivateTripsDepotIndexRoute,
  PrivateTripsDistrictIndexRoute: PrivateTripsDistrictIndexRoute,
  PrivateTripsDepotIdIndexRoute: PrivateTripsDepotIdIndexRoute,
  PrivateTripsDepotCreateIndexRoute: PrivateTripsDepotCreateIndexRoute,
  PrivateTripsDepotIdEditIndexRoute: PrivateTripsDepotIdEditIndexRoute,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(
  PrivateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
